name: clean_flutter_app
description: A new Flutter project.

publish_to: "none"

version: 0.0.1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  http: ^0.13.5
  provider: ^6.0.3
  equatable: ^2.0.3
  get: ^4.6.5
  flutter_secure_storage: ^5.1.0
  localstorage: ^4.0.0+1
  carousel_slider: ^4.1.1
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.10.0
  mockito: ^5.3.0
  faker: ^2.0.0
  test:
  test_api:

flutter:
  uses-material-design: true
